AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  books store lib application 
Globals:
  Function:
    Runtime: python3.8
    Timeout: 30
    Environment:
      Variables:
        BOOKS_TABLE: !Ref BooksTable

Resources:

  # Creating the DynamoDB database for storing the Books details
  BooksTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: isbn_id
        Type: Number
        
  # Creating the Lambda Function 
  AddBookFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: books_lib_app/
      Handler: app.lambda_handler
      Events:
        AddBook:
          Type: Api
          Properties:
            Path: /books
            Method: post
        ListBooks:
          Type: Api
          Properties:
            Path: /books
            Method: get
        DeleteBook:
          Type: Api
          Properties:
            Path: /books
            Method: delete       
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref BooksTable 
